--- #Default configuration for dweb-mirror
# Note in YAML, indentation is significant, and you can't have multiple spaces after the ":"
# Cache directory - where you want to store files, this directory must already exist
# List of places to look for the Cache directory - will check all of them, and they don't need to exist
# Paths can include unix conventions like ~ * . .. etc
# Default is to look in home directory and root of any device (for example a USB) for directories "archiveorg"
directories:
  - ~/archiveorg # Home directory of user
  - /Volumes/*/archiveorg # Any connected volume
  - /media/pi/*/archiveorg # At least on Internet-in-a-Box USB volumes are put here
  - /.data/archiveorg # This is where Rachel3+ puts its data
  - /library/archiveorg # This is where IIAB wants content
archiveui: # Where to find the ArchiveUI relative to the directory this file and the code resides in
  directories: # Note the code uses the first of these found to exist - note this should match the list in install.sh TODO figure out how to read this yaml in install.sh
    - ../dweb-archive/dist # Try a repo cloned to a directory parallel or installed to this one, which is presumably for development
    - node_modules/@internetarchive/dweb-archive/dist # Or a repo cloned during 'npm install'
connect:
  transports: # This is the list of transports that the server or crawler will use to fetch files
    - 'HTTP'
    # - 'IPFS'
    #- 'WEBTORRENT'
    #- 'GUN'
    #- 'WOLK'
  webtorrent: # Options to webtorrent
    tracker: 'wrtc'   # May or may not work on different platforms
  ipfs: # Options to IPFS
    urlUrlstore: 'http://localhost:5001/api/v0/urlstore/add'
  preferredStreamTransports: # A list, in order of preference of transports to use for streams, only works if they are listed in "connect" above.
    - 'WEBTORRENT'
    - 'HTTP'
    - 'IPFS'
# The apps group include configuration only used by one application
apps:
  # internetarchive --server uses these
  http:
    port: 4244
    morgan: ':method :url :req[range] :status :res[content-length] :response-time ms' # Used for logging
  # internetarchive --crawl  uses these
  crawl:
    # An array of tasks each consists of { identifier, level, and optional search & related
    # level is one of:
    #      tile:       sufficient to draw Tile in its parent;
    #      metadata:   including metadata info (not often used);
    #      details:    enough to render a page, including e.g. low res video
    #      all:        all files in the item - beware this can be large
    # search & related consists of sort: (only -downloads supported at present), rows: how many items to retrieve;
    #      level, search & related inside another search or related applies to the items retrieved by that search/related and nests indefinitely.
    # Leave tasks empty in configDefaults, it will get overwritten by the user's tasks.
    tasks: [ ]
    # opts controls how the search performs
    opts:
      concurrency: 10 # No more than this many tasks at a time (typically 10 open file downloads or searches
      limitTotalTasks: 300 # No more than this many tasks total (typically one per item & file.
      maxFileSize: 200000000 # Maximum size of any file retrieved
      skipCache: false # Set to true to ignore current cache contents, this is used to force the upstream server to look at each item and cache it
      skipFetchFile: false # Set to true to ignore actually fetching files, most often used for debugging
      # Default crawls if either search &| related are unspecified but crawling an item with level=detail||full
      defaultDetailsSearch:
        sort: '-downloads'
        rows: 40
        level: tile
      defaultDetailsRelated:
        sort: '-downloads'
        rows: 6
        level: tile
    # copyDirectory: /Volumes/Transcend/test2 # Testing only
#============== Dont edit anything from here on down ============================
# Information about specific URLs for services at archive.org, - should not need changing
archiveorg:
  #OBS: metadata: 'https://dweb.me/arc/archive.org/metadata'
  #OBS: servicesImg: 'https://archive.org/services/img'
  #OBS: related: 'https://be-api.us.archive.org/mds/v1/get_related/all'
  mds: 'https://be-api.us.archive.org/mds'
# Generic upstream server, should be able to parse urls like /arc or /contenthash - should not need changing
upstream: 'https://dweb.me'
